name: Code Climate Action
description: An action used to analize a project with Code Climate CLI

inputs:
  source-code:
    description: "Source code location"
    required: false
    default: "."
  timeout-seconds:
    description: "Timeout in seconds"
    required: false
    default: "900"
  codeclimate-dev:
    description: "Set to enable Code Climate --dev mode. This lets you run engines not known to the CLI"
    required: false
    default: ""
  report-stdout:
    description: "Set to print the report to STDOUT instead of generating the usual report file"
    required: false
    default: ""
  report-format:
    description: "Report format. Supported: 'json', 'html'"
    required: false
    default: "json"
  engine-memory-limit-bytes:
    description: "Set the memory limit for engines. Default: 1,024,000,000 bytes."
    required: false
    default: "1024000000"
  codeclimate-debug:
    description: "Enables Code Climate debug mode if set to 1"
    required: false
    default: "0"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source-code }}
    - ${{ inputs.timeout-seconds }}
    - ${{ inputs.codeclimate-dev }}
    - ${{ inputs.report-stdout }}
    - ${{ inputs.report-format }}
    - ${{ inputs.engine-memory-limit-bytes }}
    - ${{ inputs.codeclimate-debug }}